source 'http://rubygems.org'
gem "rails", "3.1.0.beta1"
gem "mongoid", "~> 2.0"
gem "bson_ext", "~> 1.3"
gem "will_paginate", "3.0.pre2"
gem "bcrypt-ruby", :require => "bcrypt"
gem "rspec-rails", "2.6.0.rc6", :group => [:development]
gem "nifty-generators"
gem "factory_girl_rails", :group => [:development, :test]
gem "faker", :group => [:development, :test]
gem "rspec", "2.6.0.rc6", :group => [:test]
gem "webrat", "0.7.1", :group => [:test]
gem "awesome_print", :group => [:development]
gem "heroku", :group => :development
